DES_TH_TOB_SCRIPTFILE 0x073

FUNCTIONFILE

// /////////////
# $Chat_T11	

@ 0

CHATON 0xff
	0xff $EnemyID_01 CS_RNN
	$EnemyID_01 CS_RNN "あぁ～寒い寒い。"
	$EnemyID_01 CS_RNN "こんな時期にお客様だなんて、さすがのあたいもこまるなぁ～。"
	$EnemyID_01 CS_RNN "さっさとヤっちまえばいいのか。"
	$EnemyID_01 CS_RNN "いいぞぉ～せっかくいい気分だったから、お前ら全員凍らせてやる！"
	$EnemyID_01 CS_RNN "…突っ込んでくれるやつがいないとやっぱさみしいな。"
CHATOFF

@ 1

CHATON 0xff
	$PlayerID_04 $EnemyID_01 CS_RNN
	$EnemyID_01 CS_RNN "あれ？何で冥界の住人がここに？"
	$PlayerID_04 CS_LNN "幽々子様、アイスクリームを発見しました！"
	$PlayerID_06 CS_LNN "妖夢、それかなり失礼でしょう？"
	$PlayerID_06 CS_LNN "アイスクリームに。"
	$EnemyID_01 CS_RNN "そっちかよ！"
	$EnemyID_01 CS_RNN "ちっ、後悔するなよ！あたいをバカにするな！"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_05 $EnemyID_01 CS_LNN
	$PlayerID_05 CS_LNN "⑨発見！これはこれは、カメラカメラっと。"
	$EnemyID_01 CS_RNN "⑨？モデルになれってわけ？いいな、どういうポースがいいの？"
	$PlayerID_05 CS_LNN "「あたいはバカじゃないもん」を怒鳴ってください。"
	$EnemyID_01 CS_RNN "あたいはバカじゃ…って違う！からかわないでよ！"
	$PlayerID_05 CS_LNN "あれ？引っかかれないな。"
	$EnemyID_01 CS_RNN "当然でしょ！あたいはバカじゃないもん！"
	$PlayerID_05 CS_LNN "射命丸フラッシュ！"
	$EnemyID_01 CS_RNN "しまった！言っちゃった！"
CHATOFF

@ @@[ 0

IF CHATI - 0xff !
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// /////////
# $Chat_T12


@ 1

CHATON 0xff
	$PlayerID_04 $EnemyID_02 CS_RNN
	$EnemyID_02 CS_RNN "ああもう、忙しいのに。見張りのチルノどうしたの？"
	$PlayerID_04 CS_LNN "湖と融合した。"
	$PlayerID_14 CS_LNN "⑨っていたっけ？"
	$EnemyID_02 CS_RNN "何すんのよ！いやいや、バカを頼んだ私が悪かった。"
	$PlayerID_14 CS_LNN "それより播種してるんだよね、わたしの花もまいていい？"
	$EnemyID_02 CS_RNN "農業に邪魔よ、用事ないならさっさと出ってけ！"
	$PlayerID_04 CS_LNN "あんた、麦と融合したいの？"
	$EnemyID_02 CS_RNN "いや、これ麦じゃなくて水稲よ。"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_01 $EnemyID_02 CS_RNN
	$EnemyID_02 CS_RNN "え？博麗神社は山賊に占領されたって本当？"
	$PlayerID_01 CS_LNN "山賊って…どんなうわさになってたのよ。"
	$PlayerID_02 CS_LNN "まぁ、相当違いないと思うぜ。"
	$EnemyID_02 CS_RNN "いったいどうしたの？何があったらほかの人に頼んだほうがいいぞ、私忙しいから。"
	$PlayerID_01 CS_LNN "どうやらそっちも大変そうだな。"
	$PlayerID_02 CS_LNN "腹が立つほどだな。"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_16 $EnemyID_02 CS_LFN
	$PlayerID_16 CS_LFN "おいそこの神、こっから博麗神社への道を教えて頂戴。"
	$EnemyID_02 CS_RNN "神に対してずいぶん適当な言い方ね。"
	$PlayerID_03 CS_LNN "聞こえんか、死にたくなければさっさと言え。"
	$EnemyID_02 CS_RNN "まったく、人間にまで…やっぱり一面ボスってのはひどいほど信仰不足ね。"
	$PlayerID_03 CS_LNN "そんなこと知るか。"
	$EnemyID_02 CS_RNN "じゃ教えない。こっちも大変忙しいんだから。"
	$PlayerID_16 CS_LFN "なら仕方ない、痛い目にあうぞ。"
	$EnemyID_02 CS_RNN "それはこっちのセリフ！"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_06 $EnemyID_02 CS_LNN
	$PlayerID_06 CS_LNN "あぁ～腹減った。"
	$EnemyID_02 CS_RNN "種によだれ流す幽霊ってはじめてみたわ。"
	$PlayerID_06 CS_LNN "いっただきま～す。"
	$EnemyID_02 CS_RNN "おいおい、種は食べられませんよ"
	$PlayerID_06 CS_LNN "種じゃなくて～あなたを食べますよ～。"
	$EnemyID_02 CS_RNN "ひっー！"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// //////////
# $Chat_T13

@ 1

CHATON 0xff
	$PlayerID_11 $EnemyID_09 CS_RNN
	$EnemyID_09 CS_RNN "この先は立入り禁止よ。"
	$PlayerID_11 CS_LNN "な、リリカ。この人やばくない？"
	$PlayerID_09 CS_LNN "え？どうして？ただのお巡りさんでしょう。"
	$PlayerID_11 CS_LNN "なんかいやなオーラに感じないの？かなりやばいけど。"
	$PlayerID_09 CS_LNN "そういえばそうだな、でも大丈夫、わたしたちの曲でお払いをすればいいんじゃん。"
	$PlayerID_11 CS_LNN "お払いって、巫女じゃないし。"
	$EnemyID_09 CS_RNN "ちょっ、誤魔化すな！待って！"
	$PlayerID_11 CS_LNN "あら、ばれちゃった？"
	$EnemyID_09 CS_RNN "さりげなく勝手に行くな。立入り禁止といわなかった？"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_03 $EnemyID_09 CS_RNN
	$EnemyID_09 CS_RNN "おおあわててどうしたの？"
	$PlayerID_03 CS_LNN "厄神か、寄り道でもしよっか。"
	$PlayerID_05 CS_LNN "そんな余裕どこにあるのよ。時をとまってやれ、あなたをつれてダッシュするのよ。"
	$EnemyID_09 CS_RNN "いいえ、わたしは厄をため込んでるだけだから…。"
	$PlayerID_05 CS_LNN "しっかりつかまって～"
	$EnemyID_09 CS_RNN "おいこら！無視するんでない！"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_11 $EnemyID_09 CS_LNN
	$PlayerID_11 CS_LNN "お姉さん待って、この前になんか感じてませんか。"
	$PlayerID_12 CS_LNN "ただの厄神です。"
	$EnemyID_09 CS_RNN "なんか失礼な、この先は立ち入り禁止だよ。"
	$PlayerID_11 CS_LNN "立入り禁止だって、どうする？"
	$PlayerID_12 CS_LNN "大丈夫、厄神はわたしたちの「前に進んでいけない」という悪運を吸収するはずです。"
	$EnemyID_09 CS_RNN "え？！そんなのありかよ！"
	$PlayerID_11 CS_LNN "姉さんがそういうんだから間違いわけないよ。"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_13 $EnemyID_09 CS_LFN
	$PlayerID_13 CS_LFN "。。。"
	$EnemyID_09 CS_RNN "。。。"
	$PlayerID_13 CS_LFN "なんか設定的に敵対関係を確立できるね。"
	$EnemyID_09 CS_RNN "そうよ、あんたは不幸を招いて私はそれを払う。"
	$PlayerID_13 CS_LFN "逆だよ逆！あたしは幸運をあげるほうよ！"
	$EnemyID_09 CS_RNN "どうやら自覚ないな。"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ///////
# $Chat_T14

@ 0

CHATON 0xff
	0xff $EnemyID_03 CS_RNF
	$EnemyID_03 CS_RNF "みんな集まってありがとう～。いよいよプリズムリバー楽団第二万三千五百六十回演奏始まっちゃうよ！"
	$EnemyID_06 CS_RNN "お客様は三人しかいませんだけど…。"
	$EnemyID_08 CS_RNF "二万三千五百六十回も演奏していません。わたしの計算でちょうど四百八十九回目です。"
	$EnemyID_06 CS_RNN "あらあら、さすが姉さん。"
	$EnemyID_03 CS_RNF "そんなのどうでもいいんじゃん、早速四百なんだっけ回の演奏を…。"
	$EnemyID_08 CS_RNF "ですから、四百八十九回目です。"
CHATOFF

@ 1

CHATON 0xff
	$PlayerID_08 $EnemyID_03 CS_RNF
	$EnemyID_03 CS_RNF "はいはい、そこのふたり、コンサート会場でお静かに。"
	$PlayerID_08 CS_LNN "いつからコンサートなんかになってたっけ？"
	$EnemyID_06 CS_RNN "細かいことを気にすんじゃだめよ。"
	$EnemyID_08 CS_RNF "公示をちゃんとはりました、昨日の夕方ごろに。"
	$PlayerID_10 CS_LFN "もしかしてプリズムリバー楽団なの？ぜひ握手してください！"
	$PlayerID_08 CS_LNN "え？結構有名っぽいけど、あたい全然しらないよ。"
	$EnemyID_06 CS_RNN "じゃあ、新たなファンだね、うれしいな。"
	$PlayerID_08 CS_LNN "いや、たぶんファンにならないとおもう。コンサートなのにお客様はあたいたち三人しかいないし。"
	$PlayerID_10 CS_LFN "そうだよ。やっぱりシンガーがないとだめだからな。わたしこう見ても歌に自信あるんだよ。"
	$EnemyID_08 CS_RNF "歌手はいりません。"
	$PlayerID_10 CS_LFN "即刻拒絶なんて傷つくわ。"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_05 $EnemyID_03 CS_LNF
	$PlayerID_05 CS_LNN "いいね、ちょうどコンサートのようね。"
	$EnemyID_03 CS_RNF "やばっ！天狗記者がやってきた！"
	$EnemyID_08 CS_RNF "大丈夫。ごまかしてみます。"
	$PlayerID_05 CS_LNN "おいおい聞こえますぞ。お詫びにぜひインタビューさせてください"
	$EnemyID_06 CS_RNN "お詫びのつもりなんかないよ。"
	$PlayerID_05 CS_LNN "なら普通にインタビューさせてくれ。"
	$EnemyID_03 CS_RNF "あんた演奏の邪魔になりそうだな。"
CHATOFF

@ @@[ 0

IF CHATI - 0xff !
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ///////
# $Chat_T15

@ 1

CHATON 0xff
	$PlayerID_03 $EnemyID_06 CS_RNN
	$EnemyID_06 CS_RNN "紅魔館のご方々、こちらにちょっと。"
	$PlayerID_03 CS_LNN "なんか用か？"
	$EnemyID_06 CS_RNN "担当さん～そこの吸血鬼にスポットライトを…。"
	$PlayerID_19 CS_LNN "ふん、ばかもの。"
	$EnemyID_06 CS_RNN "あれれ？効かないな。本当に吸血鬼さん？"
	$PlayerID_03 CS_LNN "効かないのは当然のこと。実は…。"
	$EnemyID_06 CS_RNN "え？こいつはパチュリーと小悪魔に中国の融合体？"
	$PlayerID_19 CS_LNN "ねぇよそんな設定！香霖の奴に紫外線カット効果があるフェースパウダーをもらったからだよ。"
	$EnemyID_06 CS_RNN "その設定こそかなり変だと思うぞ。"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_04 $EnemyID_06 CS_RNN
	$EnemyID_06 CS_RNN "あらあら、死神に半分人間。とんだ組合だね。"
	$PlayerID_04 CS_LNN "私は半分人間ではなく、半人半霊だ。"
	$EnemyID_06 CS_RNN "生きてるのか？死んでるのか？そこの死神ちゃんと仕事しろよ。"
	$PlayerID_18 CS_LNN "そんなこと私は決めません。こいつ金持ちの友達などなさそうだし。"
	$EnemyID_06 CS_RNN "なんで友達が金持ちじゃないとだめなの？三途の川を渡ってどれぐらいの金とるの？"
	$PlayerID_18 CS_LNN "教えない。それとも、一遍死んでみたい？"
	$EnemyID_06 CS_RNN "遠慮させていただきます。"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_06 $EnemyID_06 CS_LNN
	$PlayerID_06 CS_LNN "ゆかりん、彼女たち手足使わずにどうして楽器なんか弾けるの？"
	$PlayerID_22 CS_LNN "あなただって手足使わずに食事できるんじゃない？"
	$PlayerID_06 CS_LNN "え？そんなことないよ。ちゃんとお箸使ってふつうに食べますよ。"
	$PlayerID_22 CS_LNN "ふつうに、ね…。"
	$EnemyID_06 CS_RNN "漫才で応援してくれるのか～うれしいな。"
	$PlayerID_22 CS_LNN "いいえ、かなり真剣でまともな話だった。"
	$PlayerID_06 CS_LNN "私もそう思うよ。"
	$EnemyID_06 CS_RNN "あはは～あんたたち私より芸能あるんだな。"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_06 $EnemyID_06 CS_LNN
	$PlayerID_06 CS_LNN "ねぇねぇ、私も楽器を習いたいが、一番おいしい楽器ってなぁに？"
	$EnemyID_06 CS_RNN "お、おいしい？たべるつもり…ではないでしょうか…。"
	$PlayerID_06 CS_LNN "私おいしいなど言ったっけ？聞き間違いだったよね。いちばん易しい楽器だよ、やさしい。"
	$EnemyID_06 CS_RNN "あはは～そうですね。たべるわけないんだね。わたしったら…。"
	$EnemyID_06 CS_RNN "えーと、なにするつもり？！フォークなんか出して…。"
	$PlayerID_06 CS_LNN "もちろんおいしい楽器を…。"
	$EnemyID_06 CS_RNN "ッ！このひとまともじゃない！"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ////////
# $Chat_T16

@ 1

CHATON 0xff
	$PlayerID_13 $EnemyID_08 CS_RFF
	$EnemyID_08 CS_RNF "鬱です。"
	$PlayerID_13 CS_LFN "って、なに言うんだよ！コンサートのクライマックスでそれ言うと観客まで落ち込むじゃない？"
	$PlayerID_07 CS_LNN "鬱になりそうです。"
	$PlayerID_13 CS_LFN "ほら、被害者ナンバーワン発見。いったいどうしたの？わたしがいると鬱になるわけないんだよ。"
	$EnemyID_08 CS_RNF "私の憂鬱がお客様に移りそうなのだったから、鬱です。"
	$PlayerID_13 CS_LFN "。。。"
	$PlayerID_07 CS_LNN "…本当に鬱になった。"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_16 $EnemyID_08 CS_RFF
	$EnemyID_08 CS_RNF "片思い同盟…ですか…。"
	$PlayerID_16 CS_LFN "ッ！なななななに言うんだよ！私はべべべ別に…。"
	$PlayerID_07 CS_LNN "わたしまで巻き込むな！"
	$PlayerID_16 CS_LFN "だいたいあんたその表情ってなに？私を同情するつもり？ほっとけよ、もう。"
	$PlayerID_07 CS_LNN "アリス、顔真っ赤だぞ。"
	$PlayerID_16 CS_LFN "そそそそれはコンサートで盛り上げただし…けっ決してこの戯けな話題に関係ないぜ！"
	$EnemyID_08 CS_RNF "ない「ぜ」って言いましたが…。"
	$PlayerID_16 CS_LFN "あっ！今のなし！今のなし！"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_17 $EnemyID_08 CS_LNF
	$PlayerID_17 CS_LNN "うむ。なかなかのいいコンサートだった。"
	$EnemyID_08 CS_RNF "いや、まだ一曲あるんですので、席をはずしてないでください。"
	$PlayerID_14 CS_LNN "パンフレットによれば、残るのはヴァイオリン独奏の「憂鬱なメロディー」です。"
	$PlayerID_17 CS_LNN "憂鬱になりそうなので帰るぞ。"
	$EnemyID_08 CS_RNF "一応新曲ですからぜひ聞いてください。"
	$PlayerID_14 CS_LNN "そんなこと言われてもな～曲のタイトルを変えればまだ良いかも。"
	$EnemyID_08 CS_RNF "では「ブルーな旋律」ってのはどうですか。"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_22 $EnemyID_08 CS_LNF
	$PlayerID_22 CS_LNN "優等生キャラか。必要ですね、ギャルゲーに。"
	$EnemyID_08 CS_RNF "とてつもなく失礼なことを言われた気がします。鬱になりました。"
	$PlayerID_22 CS_LNN "優等生に鬱少女。萌えポイント把握したなあんた。"
	$EnemyID_08 CS_RNF "何を言いますか全然わかりませんが…。"
	$PlayerID_22 CS_LNN "別に～お忘れください。"
	$EnemyID_08 CS_RNF "ちっ、ババァのくせに…。"
	$PlayerID_22 CS_LNN "ッ！い、いまなんと！"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ////////
# $Chat_T17

@ 1

CHATON 0xff
	$PlayerID_08 $EnemyID_15 CS_RNN
	$EnemyID_15 CS_RNN "コンサートのお客様にとびっきりのインタビューを！はいそこの⑨！"
	$PlayerID_08 CS_LNN "よんだ？"
	$EnemyID_15 CS_RNN "はいはいはい。『文文。新聞』の記者ですが、さっきのプリズムリバー楽団、どうだった？感想を言ってください。"
	$PlayerID_08 CS_LNN "えーとね…。"
	$PlayerID_10 CS_LFN "やっぱり歌手がないとだめなんじゃない？"
	$EnemyID_15 CS_RNN "おぉ！これはこれは新鮮なご意見！続いて、どんな歌手がいい？"
	$PlayerID_10 CS_LFN "歌で人を狂わす程度の能力をもつといいな。"
	$EnemyID_15 CS_RNN "それはそれは、また独特なポイントオフビューだね。で、適切な人選は？"
	$PlayerID_08 CS_LNN "こーら、あたいのインタビューじゃなかったっけ？"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_08 $EnemyID_15 CS_RNN
	$EnemyID_15 CS_RNN "コンサートのお客様にとびっきりのインタビューを！はいそこの⑨！"
	$PlayerID_08 CS_LNN "よんだ？"
	$EnemyID_15 CS_RNN "はいはいはい。『文文。新聞』の記者ですが、さっきのプリズムリバー楽団、どうだった？感想を言ってください。"
	$PlayerID_08 CS_LNN "えーとね…。"
	$PlayerID_13 CS_LFN "やっぱり兎がないとだめなんじゃない？"
	$EnemyID_15 CS_RNN "。。。"
	$PlayerID_08 CS_LNN "。。。"
	$EnemyID_15 CS_RNN "続いて、感想を言ってください。"
	$PlayerID_13 CS_LFN "おい、無視するな！"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_15 $EnemyID_15 CS_LNN
	$PlayerID_15 CS_LNN "プリズムリバー楽団のサインをもらいたいな～。"
	$EnemyID_15 CS_RNN "ほほぉ～そういうお客様が多いですね、はいこれ。"
	$PlayerID_15 CS_LNN "ええ？！こ、これは、どうやって？"
	$EnemyID_15 CS_RNN "一応スタッフですから、一枚ぐらいもらえても変じゃないと思うけど？それよりあなたにインタビューしてもいい？"
	$PlayerID_15 CS_LNN "当然です！何でもしてあげるんです！"
	$PlayerID_19 CS_LNN "騙されでないぞ。それ、あいつさっき書いたばかりの偽造サインだから。"
	$PlayerID_15 CS_LNN "えっ！マジ？ってか『ブ』リズムリバーに書いたし…よくも私をバカにしてたな！"
	$EnemyID_15 CS_RNN "おっと、悪い悪い。書き直すからちょっと借りて。"
	$PlayerID_15 CS_LNN "いらないよ！あんたなんかのサイン！"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_10 $EnemyID_15 CS_LFN
	$PlayerID_10 CS_LFN "か～ごめかごめ～かごのなかのとりは～。"
	$PlayerID_10 CS_LFN "いついつであう～うしろのしょうめんだ～れ～。"
	$EnemyID_15 CS_RNN "これだから警備員が必要ね。コンサート中も勝手に歌いますし、迷惑だったのよ。"
	$PlayerID_10 CS_LFN "ひ～つようなのは～けいびいんじゃなくて～。"
	$PlayerID_10 CS_LFN "わたしのような～すてきなかしゅさん～。"
	$EnemyID_15 CS_RNN "うるさいよほんとに！"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// /////////////
# $Chat_T18

@ 0

CHATON 0xff
	0xff $EnemyID_04 CS_RNN
	$EnemyID_04 CS_RNN "で、なんのようかい？おまいらを呼ぶ覚えはないぞ。"
	$EnemyID_04 CS_RNN "これだから昆虫以外のやつが嫌いなのよ、みんな自分勝手、虫なんぞ眼にも入らん。"
	$EnemyID_04 CS_RNN "いいぞ、なら私がその出来の悪い癖を叩き直してあげる！"
	$EnemyID_04 CS_RNN "後悔しても知らんぞ。"
CHATOFF

@ 1

CHATON 0xff
	$PlayerID_07 $EnemyID_04 CS_RNN
	$EnemyID_04 CS_RNN "おいこら！善良なわが眷属に毒をやるな！ましてや食うな！"
	$PlayerID_07 CS_LNN "虫は常に毒を持っている。それが生まれつきの異能か、暗闇で感染されたのいずれにせよ、毒性は変わらない。"
	$EnemyID_04 CS_RNN "かっこつけるな！いま確実に感染されっぱなしじゃない！あんたのせいよ！"
	$PlayerID_07 CS_LNN "それこそが誠に残念なことです。"
	$PlayerID_06 CS_LNN "あらあら～パクパク。二人とも、喧嘩はいけないことよ。パクパク。"
	$EnemyID_04 CS_RNN "…食うかしゃべるかどっちにせよ！いや、だからわが眷属を食うな！"
	$PlayerID_07 CS_LNN "そうそう、毒持ちのやつを食ったら腹壊すよ。"
	$EnemyID_04 CS_RNN "ああもう！おまいらいい加減にしろ！"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_09 $EnemyID_04 CS_LNN
	$PlayerID_09 CS_LNN "このあたりはなんか光っててロマンチックってな。"
	$EnemyID_04 CS_RNN "当り前よ。われらホタルが夜光虫だから。"
	$PlayerID_09 CS_LNN "せっかくロマンになったし、みんな一緒に盛り上げようよ。"
	$EnemyID_04 CS_RNN "いや、それじゃロマンにならん。静寂こそが夜のロマンだ。"
	$PlayerID_09 CS_LNN "あんたたちこのままじゃいかんよ。人生をもっと楽しもうとしたら素晴らしいよ。"
	$EnemyID_04 CS_RNN "われわれはシンプルでいいから！"
CHATOFF

@ @@[ 0

IF CHATI - 0xff !
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ////////
# $Chat_T19

@ 1

CHATON 0xff
	$PlayerID_04 $EnemyID_05 CS_RNN
	$EnemyID_05 CS_RNN "ねぇねぇ、博麗神社のこと聞いてる？なんか物騒…って何だその目は？"
	$PlayerID_04 CS_LNN "幽々子様、今夜は焼き鳥しかいないようですが、いかがでしょうか。"
	$PlayerID_06 CS_LNN "大丈夫ですよ。それよりずいぶんと遅いですね夕食は。"
	$PlayerID_04 CS_LNN "申し訳ございません。なんか最近野生動物どもがみょんに警戒を強化しましたが、何故でしょうか。"
	$EnemyID_05 CS_RNN "！幽霊に剣士…。まさかあんたたち、うわさのなんでもイーター？"
	$PlayerID_04 CS_LNN "なによその俗っぽい名前。"
	$EnemyID_05 CS_RNN "ゆるさんぞ！同類を食いつくすの仇、いまこそここで…。"
	$PlayerID_06 CS_LNN "食材は黙りなさい～。"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_03 $EnemyID_05 CS_RNN
	$EnemyID_05 CS_RNN "な、なんでバンパイアがここに！"
	$PlayerID_03 CS_LNN "化け鳥のようです、お嬢様。"
	$PlayerID_19 CS_LNN "あいつに構う時間などない、さっさと片付けろ。"
	$PlayerID_03 CS_LNN "かしこまりました。そこの小鳥、ジャンケン勝負せよ。"
	$EnemyID_05 CS_RNN "えっ、ちょっ…あ、勝った…。"
	$PlayerID_03 CS_LNN "違う、お前の負けだ。"
	$EnemyID_05 CS_RNN "あれ？グーじゃなかったっけ？"
	$PlayerID_03 CS_LNN "バカ者。時間が止める私を勝てるとでも思ったか？"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_09 $EnemyID_05 CS_LNN
	$PlayerID_09 CS_LNN "あのさぁ～この森で演奏の練習をしてもいい？"
	$EnemyID_05 CS_RNN "大歓迎よ！もしかしてプリズムリバー楽団なの？"
	$PlayerID_12 CS_LNN "そうです。"
	$EnemyID_05 CS_RNN "わ！どどどどうしよう～。わたくし、ミスティアと申しますが…。"
	$EnemyID_05 CS_RNN "ううううたが大好きです！歌に自信があります！"
	$PlayerID_09 CS_LNN "それはよかったな。では練習始めるから…。"
	$EnemyID_05 CS_RNN "わわわたくしをプリズムリバー楽団を編入してください！"
	$PlayerID_12 CS_LNN "練習の邪魔です。"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_06 $EnemyID_05 CS_LNN
	$PlayerID_06 CS_LNN "パクっと。"
	$EnemyID_05 CS_RNN "うげっ！"
	$PlayerID_06 CS_LNN "短いチャットイベントでありました。"

CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}

// ////////
# $Chat_T1A

@ 1

CHATON 0xff
	$PlayerID_08 $EnemyID_07 CS_RNN
	$EnemyID_07 CS_RNN "今回博麗神社の騒ぎがどんな歴史に築くでしょう。"
	$PlayerID_08 CS_LNN "歴史ってやっぱ難しいな。"
	$PlayerID_12 CS_LNN "いいえ、未来のことまで歴史と認識するのもどうかと思います。"
	$EnemyID_07 CS_RNN "いずれ歴史になることを歴史と呼ぶのはどこが違うんでしょうか。"
	$PlayerID_12 CS_LNN "そのようですね。鬱になりました。"
	$PlayerID_08 CS_LNN "なんか二人ともシリアスで怖いな。"
CHATOFF

@ 2

CHATON 0xff
	$PlayerID_13 $EnemyID_07 CS_RFN
	$EnemyID_07 CS_RNN "念のため聞くけど、あんたたち邪魔する気ないよね。"
	$PlayerID_13 CS_LFN "ふぇ？何のこと？"
	$EnemyID_07 CS_RNN "禍の根源、この村を歴史から削除すること。"
	$PlayerID_15 CS_LNN "ただ通り掛かったものですから、ご自由に。"
	$EnemyID_07 CS_RNN "ではさっきのことを忘れさせてさしあげま～す。"
	$PlayerID_15 CS_LNN "ってあんたケンカ売る気？"
	$PlayerID_13 CS_LFN "あらあら、うどんげを怒らせた～。"
CHATOFF

@ 3

CHATON 0xff
	$PlayerID_16 $EnemyID_07 CS_LFN
	$PlayerID_16 CS_LFN "な、何でも聞いてくれるって本当？"
	$PlayerID_21 CS_LNN "しょうがないな。あんまりしつこいから何なりとも聞くゼ。"
	$PlayerID_16 CS_LFN "じゃあ…あの…。"
	$EnemyID_07 CS_RNN "ふっふっふ。いまのことを…忘れてくれ！"
	$PlayerID_16 CS_LFN "え？何があった？わたし、どうしてここに？"
	$PlayerID_21 CS_LNN "忘れたか、よかったゼ。白沢サンキュー。"
	$EnemyID_07 CS_RNN "うそ！なぜあんただけ忘れてない？"
	$PlayerID_21 CS_LNN "俺に通じるとでもおもったかい？"
CHATOFF

@ 4

CHATON 0xff
	$PlayerID_14 $EnemyID_07 CS_LNN
	$PlayerID_14 CS_LNN "うふふっ。あんたが例の歴史喰い、慧音か。"
	$EnemyID_07 CS_RNN "誰？"
	$PlayerID_14 CS_LNN "花畑の主、風見幽香といいます。"
	$EnemyID_07 CS_RNN "なんかご用か？"
	$PlayerID_14 CS_LNN "特にないわ。村の歴史を隠してありがとう。おかげで花は咲かすことも忘れました。"
	$EnemyID_07 CS_RNN "悪かった。"
	$PlayerID_14 CS_LNN "それですむつもり？死なすぞ！"
CHATOFF

@ @@[ 0

SD [nochat] NOW@ !
SD [nochat] TIME > 60 * nochat
IF CHATI - 0xff ! * NOW@ + nochat
{
	SETTIME 0
	SETSCENE GETSCENE + 4
}
