DES_TH_TOB_SCRIPTFILE 0x073

SCENEFILE

# $EnemyID_14	// âÏÉ¡¤ƒž•ÒÈAÔº¡¤¥¤¥Ê¥Ð`

@ POST@

CALL $SceneOff POST@

@ QUIT@

CALL $SceneOff QUIT@

@ 1

SD [blBegin] BGSI * $BGLayerSplit

IF BGSI !
{
	CALL $MusicChangeWithDisplay $MusicEID_14
}

BGVALEX 1 + blBegin SI_BG_14_2
	-40 -60 0 528 528
	0 0 0 0
	1.6 12000 true true
	0x00ffffff
BGBLEND 1 + blBegin BLEND_ALPHAADD

BGVALEX 0 + blBegin SI_BG_14_1
	-80 -80 0 608 608
	0 0 0 0
	0.9 -12000 true true
	0x00ffffff
BGBLEND 0 + blBegin BLEND_ALPHAADD

BGFLAG 1 + blBegin BG_FADEIN BGMT_FADE
BGFLAG 0 + blBegin BG_FADEINHALF BGMT_FADE

@ @@> BGMT_FADE

SD [blBegin] BGSI * $BGLayerSplit
CALLEX $SceneLightDark BGS@ 1
	1 + blBegin
