DES_TH_TOB_SCRIPTFILE 0x073

SCENEFILE

# $PlayerBombID_01	// ≤©˚ê°§ÎëâÙ

@ POST@

CALL $SceneOff POST@

@ QUIT@

CALL $SceneOff QUIT@

@ 1

SD [blBegin] BGSI * $BGLayerSplit

BGVALEX 1 + blBegin SI_PLBG_01_2
	-80 -80 0 628 628
	0 0 0 0
	0.9 -9000 true true
	0x00ffffff

BGVALUE 0 + blBegin SI_PLBG_01_1
	CenterX CenterY CenterW - 64 CenterH - 32
	0x00ffffff

BGFLAG 0 + blBegin BG_FADEIN BGMT_FADE
BGFLAG 1 + blBegin BG_FADEIN BGMT_FADE
	