#ifndef _CONSTRESOURCE_H
#define _CONSTRESOURCE_H

#include "Const.h"

//consts

#define LOG_STR_FILENAME		"TH_tamaokiba.log"

#define DATA_DEFAULTSTR_WIDE	"£¿£¿£¿£¿£¿£¿"
#define DATA_DEFAULTSTR			"????"

#define CONFIG_STR_FILENAME				"TH_tamaokiba_CONFIG.ini"
#define CONFIG_STR_DEFAULTFILENAME		"hge.ini"

#define RESDEFAULT_FONTFONT				"MS Gothic"

#define RESDEFAULT_DATARESOURCE			"TH_tamaokiba_RESOURCE.res"
#define RESDEFAULT_DATABIN				"TH_tamaokiba_BIN.databin"
#define RESDEFAULT_DATASPELLACCESS		"TH_tamaokiba_SPELLACCESS.databin"
#define RESDEFAULT_DATASCRIPT			"TH_tamaokiba_SCRIPT.databin"
#define RESDEFAULT_DATACUSTOMCONST		"TH_tamaokiba_CUSTOMCONST.table"
#define RESDEFAULT_DATASPELLDEFINE		"TH_tamaokiba_SPELLDEFINE.table"
#define RESDEFAULT_DATAMUSICDEFINE		"TH_tamaokiba_MUSICDEFINE.table"
#define RESDEFAULT_DATABULLETDEFINE		"TH_tamaokiba_BULLETDEFINE.table"
#define RESDEFAULT_ENEMYDEFINE			"TH_tamaokiba_ENEMYDEFINE.table"
#define RESDEFAULT_DATAPLAYERDEFINE		"TH_tamaokiba_PLAYERDEFINE.table"
#define RESDEFAULT_DATASPRITEDEFINE		"TH_tamaokiba_SPRITEDEFINE.table"
#define RESDEFAULT_DATAPLAYERBULLETDEFINE	"TH_tamaokiba_PLAYERBULLETDEFINE.table"
#define RESDEFAULT_DATAPLAYERSHOOTDEFINE	"TH_tamaokiba_PLAYERSHOOTDEFINE.table"
#define RESDEFAULT_DATAPLAYERGHOSTDEFINE	"TH_tamaokiba_PLAYERGHOSTDEFINE.table"

#define RESDEFAULT_SCRIPTFOLDER		"Script/"
#define RESDEFAULT_SNAPSHOTFOLDER	"SnapShot/"
#define RESDEFAULT_REPLAYFOLDER		"Replay/"
#define RESDEFAULT_DATAFOLDER		"Data/"

#define RESDEFAULT_SCRIPTEXT7		"script"
#define RESDEFAULT_REPLAYEXT7		"rpy"

#define RESDEFAULT_RPYSIGNATURE11		"DES_TH_TOB"
#define RESDEFAULT_RPYTEMPSIGN3			"rpy"
#define RESDEFAULT_RPYCOMPLETESIGN3		"RPY"
#define RESDEFAULT_RPYTAG3				"TOB"

//CONFIG
#define RESCONFIGS_RESOURCE				"Resource"
#define RESCONFIGN_RESOURCEFILE			"ResourceFile"
#define RESCONFIGDEFAULT_RESOURCEFILE		""
#define RESCONFIGN_RESBINNAME			"ResourceBinName"
#define RESCONFIGDEFAULT_RESBINNAME			RESDEFAULT_DATARESOURCE
#define RESCONFIGN_PASSWORD				"Password"
#define RESCONFIGDEFAULT_PASSWORD			"h5nc"

#define RESCONFIGS_JOYSETTING	"JoySetting"
#define RESCONFIGN_JOYFIRE		"JoyFire"
#define RESCONFIGDEFAULT_JOYFIRE	3
#define RESCONFIGN_JOYSPECIAL		"JoySpecial"
#define RESCONFIGDEFAULT_JOYSPECIAL	2
#define RESCONFIGN_JOYSLOW		"JoySlow"
#define RESCONFIGDEFAULT_JOYSLOW	7
#define RESCONFIGN_JOYCHANGE	"JoyChange"
#define RESCONFIGDEFAULT_JOYCHANGE	6
#define RESCONFIGN_JOYPAUSE		"JoyPause"
#define RESCONFIGDEFAULT_JOYPAUSE	1

#define RESCONFIGN_DEBUG_JOYSPEEDUP	"Debug_JoySpeedUp"
#define RESCONFIGDEFAULT_DEBUG_JOYSPEEDUP	5

#define RESCONFIGS_KEYSETTING	"KeySetting"
#define RESCONFIGN_KEYUP		"KeyUp"
#define RESCONFIGDEFAULT_KEYUP		DIK_UP
#define RESCONFIGN_KEYDOWN		"KeyDown"
#define RESCONFIGDEFAULT_KEYDOWN	DIK_DOWN
#define RESCONFIGN_KEYLEFT		"KeyLeft"
#define RESCONFIGDEFAULT_KEYLEFT	DIK_LEFT
#define RESCONFIGN_KEYRIGHT		"KeyRight"
#define RESCONFIGDEFAULT_KEYRIGHT	DIK_RIGHT
#define RESCONFIGN_KEYFIRE		"KeyFire"
#define RESCONFIGDEFAULT_KEYFIRE	DIK_Z
#define RESCONFIGN_KEYSPECIAL	"KeySpecial"
#define RESCONFIGDEFAULT_KEYSPECIAL	DIK_X
#define RESCONFIGN_KEYSLOW		"KeySlow"
#define RESCONFIGDEFAULT_KEYSLOW	DIK_LSHIFT
#define RESCONFIGN_KEYCHANGE	"KeyChange"
#define RESCONFIGDEFAULT_KEYCHANGE	DIK_C
#define RESCONFIGN_KEYPAUSE		"KeyPause"
#define RESCONFIGDEFAULT_KEYPAUSE	DIK_SPACE
#define RESCONFIGN_KEYSKIP		"KeySkip"
#define RESCONFIGDEFAULT_KEYSKIP	DIK_LCONTROL
#define RESCONFIGN_KEYENTER		"KeyEnter"
#define RESCONFIGDEFAULT_KEYENTER	DIK_RETURN
#define RESCONFIGN_KEYESCAPE	"KeyEscape"
#define RESCONFIGDEFAULT_KEYESCAPE	DIK_F4
#define RESCONFIGN_KEYCAPTURE	"KeyCapture"
#define RESCONFIGDEFAULT_KEYCAPTURE	DIK_HOME

#define RESCONFIGS_VOLUME		"Volume"
#define RESCONFIGN_VOLMUSIC		"Music"
#define RESCONFIGDEFAULT_VOLMUSIC	100
#define RESCONFIGN_VOLSE		"SE"
#define RESCONFIGDEFAULT_VOLSE		100

#define RESCONFIGS_CUSTOM		"Custom"
#define RESCONFIGN_SCREENMODE	"ScreenMode"
#define RESCONFIGDEFAULT_SCREENMODE	0
#define RESCONFIGN_DEFAULTLEVEL	"DefaultLevel"
#define RESCONFIGDEFAULT_DEFAULTLV	0
#define RESCONFIGN_USERNAME		"UserName"
#define RESCONFIGDEFAULT_USERNAME	"NoName"
#define RESCONFIGN_RENDERSKIP	"RenderSkip"
#define RESCONFIGDEFAULT_RENDERSKIP	0

#define RESCONFIGS_CUSTOMWINDOW		"CustomWindow"
#define RESCONFIGN_DEFAULTWINDOW	"DefaultWindow"
#define RESCONFIGDEFAULT_DEFAULTWINDOW	1
#define RESCONFIGN_WINDOWLEFT		"WindowLeft"
#define RESCONFIGDEFAULT_WINDOWLEFT		0
#define RESCONFIGN_WINDOWTOP		"WindowTop"
#define RESCONFIGDEFAULT_WINDOWTOP		0
#define RESCONFIGN_WINDOWWIDTH		"WindowWidth"
#define RESCONFIGDEFAULT_WINDOWWIDTH	640
#define RESCONFIGN_WINDOWHEIGHT		"WindowHeight"
#define RESCONFIGDEFAULT_WINDOWHEIGHT	480
#define RESCONFIGN_WINDOWTOPMOST	"WindowTopMost"
#define RESCONFIGDEFAULT_WINDOWTOPMOST	0

#define RESCONFIGS_SYSTEM			"System"
#define RESCONFIGN_USE3DMODE		"Use3DMode"
#define RESCONFIGDEFAULT_USE3DMODE		0

#define RESLOADING_PCK	"Loading.pck"
#define RESLOADING_TEX	"Loading/Loading.tex"

#define RESDEFAULT_UISTR_FILENAME		"File"
#define RESDEFAULT_UISTR_USERNAME		"Name"
#define RESDEFAULT_UISTR_SCORE			"Score"
#define RESDEFAULT_UISTR_POINT			"Point Item"
#define RESDEFAULT_UISTR_FAITH			"Faith"
#define RESDEFAULT_UISTR_ALLTIME		"Play Time"
#define RESDEFAULT_UISTR_DATE			"Date"
#define RESDEFAULT_UISTR_LOST			"Lost Rate"
#define RESDEFAULT_UISTR_BORDERRATE		"Border Rate"
#define RESDEFAULT_UISTR_FASTRATE		"Fast Rate"
#define RESDEFAULT_UISTR_MODEFLAG		"Mode"
#define RESDEFAULT_UISTR_MODE_NONE		"Normal"
#define RESDEFAULT_UISTR_MODE_PRACTICE	"Stage Practice"
#define RESDEFAULT_UISTR_MODE_SPELL		"SpellCard Practice"
#define RESDEFAULT_UISTR_USINGCHARA		"Charactors"
//#define RESDEFAULT_UISTR_MAXPLAYER		"Max Player"
#define RESDEFAULT_UISTR_MISSTIME		"Miss"
#define RESDEFAULT_UISTR_BORDERTIME		"Border"
#define RESDEFAULT_UISTR_CONTINUETIME	"Continue"
#define RESDEFAULT_UISTR_GETTIME		"SpellCard Get"
#define RESDEFAULT_UISTR_PAUSETIME		"Pause"
#define RESDEFAULT_UISTR_DIFFLV			"Level"
#define RESDEFAULT_UISTR_LASTSTAGE		"Last Stage"
#define RESDEFAULT_UISTR_GRAZE			"Graze"
#define RESDEFAULT_UISTR_CONFIRM		"OK"

#define SNAPSHOT_PRIFIX		"SnapShot"
#define SNAPSHOT_EXTENSION	"bmp"

#endif