#ifndef _PROCESSDEFINE_H
#define _PROCESSDEFINE_H

//process return value
enum
{
	PQUIT,
	PGO,
	POK,
	PBACK,
	PTURN,
	PSKIP
};
//state indicator
enum
{
	STATE_START,
	STATE_PAUSE,
	STATE_CONTINUE,
	STATE_CLEAR,
	STATE_ENDING,
	STATE_TITLE,
	STATE_PLAYER_SELECT,
	STATE_DIFFICULT_SELECT,
	STATE_OVER,
	STATE_SPELL,
	STATE_REPLAY,
	STATE_RESULT,
	STATE_OPTION,
	STATE_MUSIC,
	STATE_INIT,
};
//errorcode
enum
{
	PROC_ERROR_NONE,
	PROC_ERROR_INIFILE,
	PROC_ERROR_RESOURCE,
	PROC_ERROR_SCRIPT,
	PROC_ERROR_TRANSLATE,
	PROC_ERROR_DATA,
	PROC_ERROR_PACKAGE,
	PROC_ERROR_SOUND,
	PROC_ERROR_FONT,
	PROC_ERROR_TEXTURE
};

#define FRAME_STOPFLAG_WORLDSHAKE	0x0001
#define FRAME_STOPFLAG_PLAYER		0x0002
//#define FRAME_STOPFLAG_PLAYERSPELL	0x0004
#define FRAME_STOPFLAG_PLAYERBULLET	0x0008
#define FRAME_STOPFLAG_ENEMY		0x0010
#define FRAME_STOPFLAG_GHOST		0x0020
#define FRAME_STOPFLAG_EVENTZONE	0x0040
#define FRAME_STOPFLAG_BULLET		0x0080
#define FRAME_STOPFLAG_BEAM			0x0100
#define FRAME_STOPFLAG_ITEM			0x0200
#define FRAME_STOPFLAG_LAYER		0x0400
#define FRAME_STOPFLAG_EFFECTSP		0x1000
#define FRAME_STOPFLAG_EFFECTSYS	0x2000

#define FRAME_STOPINFOMAX	4

#define FRAME_STOPFLAGCHECK_(STOPFLAG, FLAG)	((STOPFLAG)&(FLAG))

#define FRAME_STOPFLAG_PLAYERSET	(FRAME_STOPFLAG_WORLDSHAKE|FRAME_STOPFLAG_PLAYER|FRAME_STOPFLAG_PLAYERBULLET|FRAME_STOPFLAG_LAYER|FRAME_STOPFLAG_EFFECTSYS)
#define FRAME_STOPFLAG_ENEMYSET		(FRAME_STOPFLAG_WORLDSHAKE|FRAME_STOPFLAG_ENEMY|FRAME_STOPFLAG_EVENTZONE|FRAME_STOPFLAG_BULLET|FRAME_STOPFLAG_BEAM|FRAME_STOPFLAG_ITEM|FRAME_STOPFLAG_EFFECTSP)
#define FRAME_STOPFLAG_ALLSET		(FRAME_STOPFLAG_WORLDSHAKE|FRAME_STOPFLAG_PLAYER|FRAME_STOPFLAG_PLAYERBULLET|FRAME_STOPFLAG_ENEMY|FRAME_STOPFLAG_EVENTZONE|FRAME_STOPFLAG_BULLET|FRAME_STOPFLAG_BEAM|FRAME_STOPFLAG_ITEM|FRAME_STOPFLAG_LAYER|FRAME_STOPFLAG_EFFECTSP|FRAME_STOPFLAG_EFFECTSYS)

#endif