#ifndef _SCRIPTERDEFINES_H
#define _SCRIPTERDEFINES_H

#define SCRIPT_CTOFFSET	0xA000

#define SCR_NULL_STR		"_NULL"
#define SCR_CONST_STR		"_CONST"
#define SCR_KEYSTATE_STR	"_KEYSTATE"

enum{
	SCR_TYPEBEGIN	= 0xAFFFAA00,

	SCR_SCRIPTTAG	= 0xAFFFAB00,

	SCR_FILENAME	= 0xAFFFAC10,
	SCR_BLOCKCON	= 0xAFFFAC20,

	SCR_CONTROL		= 0xAFFFAD10,
	SCR_STAGE		= 0xAFFFAD20,
	SCR_EDEF		= 0xAFFFAD40,
	SCR_SCENE		= 0xAFFFAD80,
	SCR_FUNCTION	= 0xAFFFAE10,
	SCR_EVENT		= 0xAFFFAE20,

	SCR_CTCONTROL	= SCR_CONTROL - SCRIPT_CTOFFSET,
	SCR_CTSTAGE		= SCR_STAGE - SCRIPT_CTOFFSET,
	SCR_CTEDEF		= SCR_EDEF - SCRIPT_CTOFFSET,
	SCR_CTSCENE		= SCR_SCENE - SCRIPT_CTOFFSET,
	SCR_CTFUNCTION	= SCR_FUNCTION - SCRIPT_CTOFFSET,
	SCR_CTEVENT		= SCR_EVENT - SCRIPT_CTOFFSET,

	SCR_NULL		= 0xAFFFAF00,
	SCR_CONST		= 0xAFFFAF10,
	SCR_KEYSTATE	= 0xAFFFAF20,
};

#define SCRKT_STR_TIMEFUNC		"@@"

#define SCRKT_SIZE_TIMEFUNC		2
#define SCRKT_SIZE_OPERATOR		3
#define SCRKT_TEST_OPERATOR		0x7
#define SCRKT_SIZE_OPERATORNUM	8

#define SCRKT_CHAR_MOD			'%'
#define SCRKT_CHAR_PLUS			'+'
#define SCRKT_CHAR_LESS			'<'
#define SCRKT_CHAR_LESSEQUAL	']'
#define SCRKT_CHAR_EQUAL		'='
#define SCRKT_CHAR_GREATEQUAL	'['
#define SCRKT_CHAR_GREAT		'>'

#define SCR_TIMECONTROL			0xF0000000
#define SCR_TIMECONTROL_TEST0	0x08000000

#define SCR_TIMEFUNC_MOD		0x1
#define SCR_TIMEFUNC_PLUS		0x2
#define SCR_TIMEFUNC_TESTERBEGIN	0x3
#define SCR_TIMEFUNC_LESS		0x3
#define SCR_TIMEFUNC_LESSEQUAL	0x4
#define SCR_TIMEFUNC_EQUAL		0x5
#define SCR_TIMEFUNC_GREATEQUAL	0x6
#define SCR_TIMEFUNC_GREAT		0x7

enum {
	/*UIEvent*/

	SCR_EVENT_ENTERSTATE		= 0x0010,
	SCR_EVENT_LEAVESTATE		= 0x0020,

	/*Player*/
	SCR_EVENT_PLAYERBOMB	= 0x01A0,
	/*Bullet*/
	SCR_EVENT_BULLETENTERIZE	= 0x0210,
	/*0x20*/
};

#endif